# === Production Dockerfile ===
FROM oven/bun:1-alpine
COPY good-food-contracts /good-food-contracts
WORKDIR /app
COPY package.json bun.lockb* bun.lock* ./
RUN bun install --production
COPY . .
RUN bunx prisma generate
EXPOSE 8080
CMD ["bun", "run", "src/app.ts"]
